//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee.Model
{
    using Coffee.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Account : BaseViewModel
    {
        private int _id { get; set; }
        public int id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private string _DisplayName { get; set; }
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        private string _UserName { get; set; }
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }
        private string _PassWord { get; set; }
        public string PassWord { get => _PassWord; set { _PassWord = value; OnPropertyChanged(); } }
        public int RoleID { get; set; }



        public virtual AccountRole AccountRole { get; set; }
    }
}
