//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee.Model
{
    using Coffee.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Menu : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.BillInfoes = new HashSet<BillInfo>();
        }
    
        public int id { get; set; }
        private string _Name;
        public string Name { get => _Name; set { _Name = value; OnPropertyChanged(); } }
        private int _CategoryID;
        public int CategoryID { get => _CategoryID; set { _CategoryID = value; OnPropertyChanged(); } }
        private double _Price;
        public double Price { get => _Price; set { _Price = value; OnPropertyChanged(); } }

 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
        public virtual FoodCategory FoodCategory { get; set; }
    }
}
